version: '3.3'
services:
  streamer:
    image: joydeep/near-streamer
    volumes:
      - .aws:/root/.aws/
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27018/
      - NETWORK=mainnet
      - START_BLOCK=114756144
      - PORT=6901
      - ALERTER_ACTIVE=true
      - PRUNE_AFTER=604800
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    ports:
      - '6901:6901'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    command: mongod --port 27018
    ports:
      - '27018:27018'
    volumes:
      - ./db-alpha:/data/db:rw