version: '3.3'
services:
  streamer:
    image: docker.io/joydeep/near-streamer:4.0
    volumes:
      - ~/.aws:/root/.aws/
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27018/
      - NETWORK=testnet
      - START_BLOCK=146791266
      - PORT=6901
      - ALERTER_ACTIVE=true
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    ports:
      - '6901:6901'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    command: mongod --port 27018
    ports:
      - '27018:27018'
    volumes:
      - ./db-alpha:/data/db:rw